window.publicationsData = [
  {
    year: 2026,
    short: "ECCV",
    title: "InverseCrafter: Efficient Video ReCapture as a Latent Domain Inverse Problem",
    authors: "Yeobin Hong*, Suhyeon Lee*, Hyungjin Chung+, Jong Chul Ye+",
    venue: "European Conference on Computer Vision, 2026.",
    image: "assets/images/inversecrafter.jpg",
    links: [
      ["Paper", "https://arxiv.org/abs/2512.05672"],
      ["Code", "https://github.com/yeobinhong/InverseCrafter"],
    ],
  },
  {
    year: 2026,
    short: "ECCV",
    title: "ReDesign: Recovering Editable Design Structures from Raster Images via Agentic Decomposition",
    authors: "Jooyeol Yun, Jintae Park, Hyesu Lim, Junha Hyung, Hyungjin Chung, Jaegul Choo",
    venue: "European Conference on Computer Vision, 2026.",
    image: "assets/images/redesign.jpg",
    links: [
      ["Paper", "https://openreview.net/forum?id=JiEr8B3WBr"],
      ["Code", "https://github.com/jintae-00/ReDesign"],
      ["Project", "https://jintae-00.github.io/ReDesign/"],
    ],
  },
  {
    year: 2026,
    short: "ICML",
    title: "ContrastiveCFG: Guiding Diffusion Sampling by Contrasting Positive and Negative Concepts",
    authors: "Jinho Chang, Changsun Lee, Hyungjin Chung, Jong Chul Ye",
    venue: "International Conference on Machine Learning, 2026.",
    image: "assets/images/contrastive-cfg.png",
    links: [["Paper", "https://arxiv.org/abs/2411.17077"]],
  },
  {
    year: 2026,
    short: "CVPR",
    title: "ReDirector: Robust Video Diffusion with Reversible Frame Reordering",
    authors: "Byeongjun Park, Byung-Hoon Kim, Hyungjin Chung+, Jong Chul Ye+",
    venue: "IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2026.",
    image: "assets/images/redirector.jpg",
    links: [
      ["Paper", "https://arxiv.org/abs/2511.19827"],
      ["Code", "https://github.com/byeongjun-park/ReDirector"],
      ["Project", "https://byeongjun-park.github.io/ReDirector/"],
    ],
  },
  {
    year: 2026,
    short: "CVPR Findings",
    title: "Video Parallel Scaling: Aggregating Diverse Frame Subsets for VideoLLMs",
    authors: "Hyungjin Chung, Hyelin Nam, Jiyeon Kim, Hyojun Go, Byeongjun Park, Junho Kim, Joonseok Lee, Seongsu Ha, Byung-Hoon Kim",
    venue: "IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2026.",
    image: "assets/images/publications/vps.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2509.08016"],
      ["Code", "https://github.com/hyungjin-chung/VPS"],
    ],
  },
  {
    year: 2026,
    short: "ICLR",
    title: "Stochastic Optimal Control for Continuous-Time fMRI Representation Learning",
    authors: "Joonhyeong Park*, Byoungwoo Park, Chang-Bae bang, Jungwon Choi, Hyungjin Chung, Byung-Hoon Kim+, Juho Lee+",
    venue: "International Conference on Learning Representations, 2026.",
    image: "assets/images/publications/bdo.webp",
    links: [["Paper", "https://openreview.net/forum?id=N51nP3TBwR"]],
  },
  {
    year: 2025,
    short: "NeurIPS",
    title: "InvFusion: Bridging Supervised and Zero-shot Diffusion for Inverse Problems",
    authors: "Noam Elata*, Hyungjin Chung*, Jong Chul Ye, Tomer Michaeli, Michael Elad",
    venue: "Advances in Neural Information Processing Systems, 2025.",
    image: "assets/images/publications/invfusion.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2504.01689"],
      ["Code", "https://github.com/noamelata/InvFusion"],
    ],
  },
  {
    year: 2025,
    short: "ICCV",
    title: "SteerX: Creating Any Camera-Free 3D and 4D Scenes with Geometric Steering",
    authors: "Byeongjun Park*, Hyojun Go*, Hyelin Nam, Byung-Hoon Kim, Hyungjin Chung+, Changick Kim+",
    venue: "IEEE/CVF International Conference on Computer Vision, 2025.",
    image: "assets/images/publications/steerx.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2503.12024"],
      ["Code", "https://github.com/byeongjun-park/SteerX"],
      ["Project", "https://byeongjun-park.github.io/SteerX/"],
    ],
  },
  {
    year: 2025,
    short: "ICCV",
    title: "VideoRFSplat: Direct Scene-Level Text-to-3D Gaussian Splatting Generation with Flexible Pose and Multi-View Joint Modeling",
    authors: "Hyojun Go*, Byeongjun Park*, Hyelin Nam, Byung-Hoon Kim, Hyungjin Chung+, Changick Kim+",
    venue: "IEEE/CVF International Conference on Computer Vision, 2025.",
    image: "assets/images/publications/videorfsplat.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2503.15855"],
      ["Code", "https://github.com/gohyojun15/VideoRFSplat"],
      ["Project", "https://gohyojun15.github.io/VideoRFSplat/"],
    ],
  },
  {
    year: 2025,
    short: "ICCV",
    title: "CapeLLM: Support-Free Category-Agnostic Pose Estimation with Multimodal Large Language Models",
    authors: "Junho Kim, Hyungjin Chung+, Byung-Hoon Kim+",
    venue: "IEEE/CVF International Conference on Computer Vision, 2025.",
    image: "assets/images/publications/capellm.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2411.06869"],
      ["Code", "https://github.com/Junhojuno/CapeLLM"],
    ],
  },
  {
    year: 2025,
    short: "CVPR",
    title: "Derivative-Free Diffusion Manifold-Constrained Gradient for Unified XAI",
    authors: "Won Jun Kim*, Hyungjin Chung*, Jaemin Kim*, Sangmin Lee, Byeongsu Sim, Jong Chul Ye",
    venue: "IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2025.",
    image: "assets/images/publications/freemcg.webp",
    links: [["Paper", "https://arxiv.org/abs/2411.15265"]],
  },
  {
    year: 2025,
    short: "ICLR",
    title: "CFG++: Manifold-constrained Classifier Free Guidance for Diffusion Models",
    authors: "Hyungjin Chung*, Jeongsol Kim*, Geon Yeong Park*, Hyelin Nam*, Jong Chul Ye",
    venue: "International Conference on Learning Representations, 2025.",
    note: "Silver prize, 31st Samsung Humantech Paper Award",
    image: "assets/images/publications/cfgpp.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2406.08070"],
      ["Code", "https://github.com/CFGpp-diffusion/CFGpp"],
      ["Project", "https://cfgpp-diffusion.github.io/"],
    ],
  },
  {
    year: 2025,
    short: "ICLR",
    title: "Regularization by texts for latent diffusion inverse solvers",
    authors: "Jeongsol Kim*, Geon Yeong Park*, Hyungjin Chung, Jong Chul Ye",
    venue: "International Conference on Learning Representations, 2025.",
    note: "Spotlight presentation",
    image: "assets/images/publications/treg.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2311.15658"],
      ["Code", "https://github.com/TReg-inverse/TReg"],
      ["Project", "https://treg-inverse.github.io/treg-inverse/"],
    ],
  },
  {
    year: 2025,
    short: "IEEE TMI",
    title: "Steerable Conditional Diffusion for Out-of-Distribution Adaptation in Medical Image Reconstruction",
    authors: "Riccardo Barbano*, Alexander Denker*, Hyungjin Chung*, Tae Hoon Roh, Simon Arrdige, Peter Maass, Bangti Jin, Jong Chul Ye",
    venue: "IEEE Transactions on Medical Imaging, 2025.",
    image: "assets/images/publications/scd.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2308.14409"],
      ["Code", "https://github.com/alexdenker/SteerableConditionalDiffusion"],
    ],
  },
  {
    year: 2024,
    short: "IEEE JBHI",
    title: "Fundus image enhancement through direct diffusion bridges",
    authors: "Sehui Kim*, Hyungjin Chung*, Se Hie Park, Eui-Sang Chung, Kayoung Yi, Jong Chul Ye",
    venue: "IEEE Journal of Biomedical and Health Informatics, 2024.",
    image: "assets/images/publications/fd3.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2409.12377"],
      ["Code", "https://github.com/heeheee888/FD3"],
    ],
  },
  {
    year: 2024,
    short: "ECCV",
    title: "Deep Diffusion Image Prior for Efficient OOD Adaptation in 3D Inverse Problems",
    authors: "Hyungjin Chung, Jong Chul Ye",
    venue: "European Conference on Computer Vision, 2024.",
    note: "Gold prize, 30th Samsung Humantech Paper Award",
    image: "assets/images/publications/ddip.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2407.10641"],
      ["Code", "https://github.com/HJ-harry/DDIP3D"],
    ],
  },
  {
    year: 2024,
    short: "ICML",
    title: "Prompt-tuning Latent Diffusion Models for Inverse Problems",
    authors: "Hyungjin Chung, Jong Chul Ye, Peyman Milanfar, Mauricio Delbracio",
    venue: "International Conference on Machine Learning, 2024.",
    image: "assets/images/publications/p2l.webp",
    links: [["Paper", "https://arxiv.org/abs/2310.01110"]],
  },
  {
    year: 2024,
    short: "ICLR",
    title: "Decomposed Diffusion Sampler for Accelerating Large-Scale Inverse Problems",
    authors: "Hyungjin Chung, Suhyeon Lee, Jong Chul Ye",
    venue: "International Conference on Learning Representations, 2024.",
    image: "assets/images/publications/dds.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2303.05754"],
      ["Code", "https://github.com/HJ-harry/DDS"],
    ],
  },
  {
    year: 2023,
    short: "ICCV",
    title: "Improving 3D Imaging with Pre-Trained Perpendicular 2D Diffusion Models",
    authors: "Suhyeon Lee*, Hyungjin Chung*, Minyoung Park, Jonghyuk Park, Wi-Sun Ryu, Jong Chul Ye",
    venue: "IEEE/CVF International Conference on Computer Vision, 2023.",
    image: "assets/images/publications/tpdm.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2303.08440"],
      ["Code", "https://github.com/hyn2028/tpdm"],
    ],
  },
  {
    year: 2023,
    short: "CVPR",
    title: "Parallel Diffusion Models of Operator and Image for Blind Inverse Problems",
    authors: "Hyungjin Chung*, Jeongsol Kim*, Sehui Kim, Jong Chul Ye",
    venue: "IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2023.",
    image: "assets/images/publications/blinddps.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2211.10656v1"],
      ["Code", "https://github.com/BlindDPS/blind-dps"],
      ["Project", "https://blinddps.github.io/blind-dps-project/"],
      ["Video", "https://www.youtube.com/watch?v=uQx63WUOIj0"],
    ],
  },
  {
    year: 2023,
    short: "CVPR",
    title: "Solving 3D Inverse Problems using Pre-trained 2D Diffusion Models",
    authors: "Hyungjin Chung*, Dohoon Ryu*, Michael T. Mccann, Marc L. Klasky, Jong Chul Ye",
    venue: "IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2023.",
    image: "assets/images/publications/diffusionmbir.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2211.10655v1"],
      ["Code", "https://github.com/HJ-harry/DiffusionMBIR"],
      ["Video", "https://www.youtube.com/watch?v=M-SQLJr5hDQ"],
    ],
  },
  {
    year: 2023,
    short: "ICLR",
    title: "Diffusion Posterior Sampling for General Noisy Inverse Problems",
    authors: "Hyungjin Chung*, Jeongsol Kim*, Michael T. Mccann, Marc L. Klasky, Jong Chul Ye",
    venue: "International Conference on Learning Representations, 2023.",
    note: "Spotlight; Gold prize, 29th Samsung Humantech Paper Award",
    image: "assets/images/publications/dps.webp",
    links: [
      ["Paper", "https://openreview.net/forum?id=OnD9zGAGT0k"],
      ["Code", "https://github.com/DPS2022/diffusion-posterior-sampling"],
      ["Project", "https://dps2022.github.io/diffusion-posterior-sampling-page/"],
    ],
  },
  {
    year: 2022,
    short: "NeurIPS",
    title: "Improving Diffusion Models for Inverse Problems using Manifold Constraints",
    authors: "Hyungjin Chung*, Byeongsu Sim*, Dohoon Ryu, Jong Chul Ye",
    venue: "Advances in Neural Information Processing Systems, 2022.",
    image: "assets/images/publications/mcg.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2206.00941"],
      ["Code", "https://github.com/HJ-harry/MCG_diffusion"],
    ],
  },
  {
    year: 2022,
    short: "CVPR",
    title: "Come-Closer-Diffuse-Faster: Accelerating Conditional Diffusion Models for Inverse Problems through Stochastic Contraction",
    authors: "Hyungjin Chung, Byeongsu Sim, Jong Chul Ye",
    venue: "IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2022.",
    image: "assets/images/publications/ccdf.webp",
    links: [["Paper", "https://arxiv.org/abs/2112.05146"]],
  },
  {
    year: 2022,
    short: "IEEE TMI",
    title: "MR Image Denoising and Super-Resolution Using Regularized Reverse Diffusion",
    authors: "Hyungjin Chung, Eun Sun Lee, Jong Chul Ye",
    venue: "IEEE Transactions on Medical Imaging, 2022.",
    image: "assets/images/publications/r2d2.webp",
    links: [["Paper", "https://arxiv.org/abs/2203.12621"]],
  },
  {
    year: 2022,
    short: "MeDIA",
    title: "Score-based diffusion models for accelerated MRI",
    authors: "Hyungjin Chung, Jong Chul Ye",
    venue: "Medical Image Analysis, 2022.",
    image: "assets/images/publications/score-mri.webp",
    links: [
      ["Paper", "https://arxiv.org/abs/2110.05243"],
      ["Code", "https://github.com/HJ-harry/score-MRI"],
    ],
  },
  {
    year: 2022,
    short: "ACS Nano",
    title: "Low-dose sparse-view HAADF-STEM-EDX tomography of nanocrystals using unsupervised deep learning",
    authors: "Eunju Cha*, Hyungjin Chung*, Jaeduck Jang, Junho Lee, Eunha Lee, Jong Chul Ye",
    venue: "ACS Nano, 2022.",
    image: "assets/images/publications/acs_nano.gif",
    links: [["Paper", "https://pubs.acs.org/doi/10.1021/acsnano.2c00168"]],
  },
  {
    year: 2021,
    short: "GIE",
    title: "Deep Learning Model for Diagnosing Gastric Mucosal Lesions Using Endoscopic Images: Development, Validation, and Method Comparison",
    authors: "Joon Yeul Nam*, Hyungjin Chung*, Kyu Sung Choi*, Hyuk Lee*, Seung Jun Han*, Tae Jun Kim, Hosim Soh, Eun Kang, Soo-jeong Cho, Jong Chul Ye, Jong Pil Im, Sang Gyun Kim, Yoon Jun Kim, Joo Sung Kim, Jung-Hwan Yoo, Hyunsoo Chung, Jeong-Hoon Lee",
    venue: "Gastrointestinal Endoscopy, 2021.",
    image: null,
    links: [["Paper", "https://pubmed.ncbi.nlm.nih.gov/34492271/"]],
  },
  {
    year: 2021,
    short: "Nat. Mach. Intell.",
    title: "Deep learning STEM-EDX tomography of nanocrystals",
    authors: "Yoseob Han*, Jaeduck Jang*, Eunju Cha*, Junho Lee*, Hyungjin Chung*, Myoungho Jeong, Tae-Gon Kim, Byeong Gyu Chae, Hee Goo Kim, Shinae Jun, Sungwoo Hwang, Eunha Lee, Jong Chul Ye",
    venue: "Nature Machine Intelligence, 2021.",
    note: "2021 March Issue Cover",
    image: "assets/images/publications/NMI_stem.webp",
    links: [
      ["Paper", "https://www.nature.com/articles/s42256-020-00289-5"],
      ["Code", "https://github.com/bispl-kaist/Deep-Learning-STEM-EDX-Tomography/tree/master/Deep_Learning_STEM-EDX_Tomography"],
    ],
  },
  {
    year: 2021,
    short: "Nat. Mach. Intell.",
    title: "Reusability report: Feature disentanglement in generating a three-dimensional structure from a two-dimensional slice with sliceGAN",
    authors: "Hyungjin Chung, Jong Chul Ye",
    venue: "Nature Machine Intelligence, 2021.",
    image: "assets/images/publications/NMI_feat.webp",
    links: [
      ["Paper", "https://www.nature.com/articles/s42256-021-00400-4"],
      ["Code", "https://github.com/HJ-harry/SliceGAN_AdaIN"],
    ],
  },
  {
    year: 2021,
    short: "IEEE SPM",
    title: "Unsupervised Deep Learning Methods for Biological Image Reconstruction and Enhancement",
    authors: "Mehmet Akcakaya, Burhaneddin Yaman, Hyungjin Chung, Jong Chul Ye",
    venue: "IEEE Signal Processing Magazine, 2021.",
    image: null,
    links: [["Paper", "https://arxiv.org/abs/2105.08040"]],
  },
  {
    year: 2020,
    short: "MeDIA",
    title: "Two-Stage Deep Learning for Accelerated 3D Time-of-Flight MRA without Matched Training Data",
    authors: "Hyungjin Chung, Eunju Cha, Leonard Sunwoo, Jong Chul Ye",
    venue: "Medical Image Analysis, 2020.",
    image: "assets/images/publications/MeDIA_TOF.webp",
    links: [["Paper", "https://www.sciencedirect.com/science/article/abs/pii/S1361841521000931"]],
  },
  {
    year: 2020,
    short: "IEEE TCI",
    title: "Missing Cone Artifacts Removal in ODT using Unsupervised Deep Learning in Projection Domain",
    authors: "Hyungjin Chung, Jaeyoung Huh, Geon Kim, Yong Keun Park, Jong Chul Ye",
    venue: "IEEE Transactions on Computational Imaging, 2020.",
    image: "assets/images/publications/TCI_missing_cone.webp",
    links: [["Paper", "https://ieeexplore.ieee.org/abstract/document/9495275"]],
  },
  {
    year: 2020,
    short: "IEEE TCI",
    title: "Unpaired training of deep learning tMRA for flexible spatio-temporal resolution",
    authors: "Gyutaek Oh, Byeongsu Sim, Hyungjin Chung, Leonard Sunwoo, Jong Chul Ye",
    venue: "IEEE Transactions on Computational Imaging, 2020.",
    image: null,
    links: [["Paper", "https://arxiv.org/abs/2008.12967"]],
  },
  {
    year: 2020,
    short: "IEEE TMI",
    title: "Unpaired training of deep learning tMRA for flexible spatio-temporal resolution",
    authors: "Eunju Cha, Hyungjin Chung, Eung Yeop Kim, Jong Chul Ye",
    venue: "IEEE Transactions on Medical Imaging, 2020.",
    image: null,
    links: [["Paper", "https://pubmed.ncbi.nlm.nih.gov/32915733/"]],
  },
];
